# Generated by Django 5.2.5 on 2025-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_project_options_alter_team_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/"
            ),
        ),
    ]
