# Generated by Django 5.2.5 on 2025-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_worker_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Зображення профілю користувача",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
