# Generated by Django 5.2.5 on 2025-08-27 13:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_worker_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Image for profile",
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
