# Generated by Django 5.2.5 on 2025-09-10 09:18

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_worker_avatar"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="deadline_not_before_created",
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deadline__isnull", True),
                    (
                        "deadline__gte",
                        django.db.models.functions.datetime.TruncDate("created_at"),
                    ),
                    _connector="OR",
                ),
                name="deadline_not_before_created",
            ),
        ),
    ]
